### ISSUE TITLE
是不是写完测试崩溃信息的代码后忘删了……

### ISSUE THREAD

**Issue by Kouchya** [H2Sxxa/TouhouTweaks#1]
1.12.2 Forge 14.23.5.2859，装了这个模组后每次启动游戏都直接在预加载阶段弹莫名其妙的 Test Crash 异常，过来一翻源码发现……

```Java
@EventHandler
public void preInit(FMLPreInitializationEvent event) throws Exception{
    logger = event.getModLog();
    ModSounds.initModSounds();
    throw new Exception("Test Crash");
}
```

我不好说……作者你看下吧 @H2Sxxa

**Comment by H2Sxxa** [comment]
草，还真是忘记删了，我速度处理一下，主要是没见到人给我反馈（

应该是Git推送的时候出了问题，我本地版本删掉了

**Comment by H2Sxxa** [comment]
https://github.com/H2Sxxa/TouhouTweaks/releases/tag/v1.2
